# Generated by Django 4.1 on 2022-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCompared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=100)),
                ('username2', models.CharField(max_length=100)),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
