# Generated by Django 4.1 on 2022-08-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userscompared_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=50)),
                ('match_data', models.CharField(max_length=999999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
