# Generated by Django 4.1 on 2022-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_matchinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
